uic forms/QtdSyncDlg.ui -o ui_QtdSyncDlg.h
uic forms/QtdSyncStartupDlg.ui -o ui_QtdSyncStartupDlg.h
uic forms/QtdSyncConfigDlg.ui -o ui_QtdSyncConfigDlg.h
uic forms/QtdSyncAboutDlg.ui -o ui_QtdSyncAboutDlg.h
uic forms/QtdSyncAuthDlg.ui -o ui_QtdSyncAuthDlg.h
uic forms/QtdSyncRemoteUserDlg.ui -o ui_QtdSyncRemoteUserDlg.h
uic forms/QtdSyncUpdateDlg.ui -o ui_QtdSyncUpdateDlg.h
uic forms/QtdSyncScheduledBackupDlg.ui -o ui_QtdSyncScheduledBackupDlg.h
uic forms/QtdSyncSettingsDlg.ui -o ui_QtdSyncSettingsDlg.h
uic forms/QtdSyncServerDlg.ui -o ui_QtdSyncServerDlg.h
uic forms/QtdSyncVDirConfigDlg.ui -o ui_QtdSyncVDirConfigDlg.h
uic forms/QtdSyncSSHFolderDlg.ui -o ui_QtdSyncSSHFolderDlg.h
uic forms/QtdSyncFolderBindingDlg.ui -o ui_QtdSyncFolderBindingDlg.h
uic forms/QtdSyncMailDlg.ui -o ui_QtdSyncMailDlg.h
uic forms/QtdSyncScheduleDlg.ui -o ui_QtdSyncScheduleDlg.h
